### ISSUE TITLE
Exercices Segfaults

### ISSUE THREAD

**Issue by up4** [thlorenz/learnuv#22] opened 2016-06-29 01:19 UTC
As per IRC conversation here: http://logs.libuv.org/libuv/2016-06-29

Apparently, it is an access violation problem with the buffer.

**Comment by saghul** [comment] 2016-06-29 09:06
This is a duplicate of #20.

**Comment by up4** [comment] 2016-06-29 17:33
ok thanks.

**Closed** 2017-03-04 21:47 UTC
